version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    command:
      [
        "--sampling.strategies-file=/etc/jaeger/sampling_strategies.json",
        "--log-level=debug",
      ]
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
